# Generated by Django 3.2.8 on 2021-11-01 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movement',
            table='movement',
        ),
    ]
