# Generated by Django 3.2.7 on 2021-09-11 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyRecord', '0001_initial'),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantityBought', models.IntegerField(default=0)),
                ('pppBought', models.DecimalField(decimal_places=2, max_digits=6)),
                ('buyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyRecord.buyrecord')),
                ('prodId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
            options={
                'unique_together': {('buyId', 'prodId')},
            },
        ),
    ]
