# Generated by Django 3.2.8 on 2021-11-01 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuyLog', '0002_remove_buylog_pppbought'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='buylog',
            table='buylog',
        ),
    ]
