# Generated by Django 3.2.7 on 2021-09-11 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
        ('buyRecord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyrecord',
            name='provrId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedor.proveedor'),
        ),
    ]
