# Generated by Django 3.2.8 on 2021-11-01 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyRecord', '0002_alter_buyrecord_provrid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='buyrecord',
            table='buyrecord',
        ),
    ]
