# Generated by Django 3.2.8 on 2021-11-01 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellRecord', '0002_alter_sellrecord_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sellrecord',
            table='sellrecord_sellrecord',
        ),
    ]
