# Generated by Django 3.2.7 on 2021-09-11 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellLog', '0001_initial'),
        ('sellRecord', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selllog',
            name='sellId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellRecord.sellrecord'),
        ),
        migrations.AlterUniqueTogether(
            name='selllog',
            unique_together={('sellId', 'prodId')},
        ),
    ]
