# Generated by Django 3.2.7 on 2021-09-28 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellLog', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selllog',
            name='pppSold',
        ),
    ]
