# Generated by Django 3.2.8 on 2021-11-01 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellLog', '0003_remove_selllog_pppsold'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='selllog',
            table='selllog',
        ),
    ]
