# Generated by Django 3.2.7 on 2021-09-16 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='provEmail',
        ),
    ]
