# Generated by Django 3.2.6 on 2021-10-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0002_remove_proveedor_provemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='provName',
            field=models.CharField(max_length=32),
        ),
    ]
