# Generated by Django 3.2.8 on 2021-11-01 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0003_alter_proveedor_provname'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='proveedor',
            table='proveedor',
        ),
    ]
