# Generated by Django 3.2.7 on 2021-09-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('prodId', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('prodName', models.CharField(max_length=64)),
                ('buyPrice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sellPrice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock', models.IntegerField(default=0)),
                ('presentacion', models.CharField(choices=[('1', 'Unidad'), ('2', 'Kilogramo')], max_length=20)),
            ],
        ),
    ]
