# Generated by Django 3.2.8 on 2021-11-01 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_alter_producto_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producto',
            table='producto_producto',
        ),
    ]
